package org.example.appointment_system.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;
import java.time.LocalTime;

/**
 * AppointmentSlot entity representing a time slot within an appointment task.
 *
 * <p>This entity represents a specific time slot that users can book.
 * Each slot belongs to an appointment task and has its own capacity limit.</p>
 *
 * <p>The entity contains:</p>
 * <ul>
 *   <li>Associated appointment task</li>
 *   <li>Start and end time</li>
 *   <li>Maximum capacity for this slot</li>
 *   <li>Current booking count</li>
 * </ul>
 *
 * <p>Concurrency control:</p>
 * <p>The bookedCount field should be updated atomically when creating bookings.
 * Use optimistic locking at the booking level to handle concurrent reservations.</p>
 */
@Entity
@Table(name = "appointment_slots", indexes = {
    @Index(name = "idx_slot_task_id", columnList = "task_id"),
    @Index(name = "idx_slot_time", columnList = "start_time, end_time")
})
@Getter
@Setter
@NoArgsConstructor
public class AppointmentSlot {

    /**
     * Unique identifier for the appointment slot.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The appointment task that this slot belongs to.
     * Many-to-one relationship with AppointmentTask.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "task_id", nullable = false)
    private AppointmentTask task;

    /**
     * The start time of the slot.
     * Stored as LocalTime since the date is in the parent task.
     */
    @Column(name = "start_time", nullable = false)
    private LocalTime startTime;

    /**
     * The end time of the slot.
     * Stored as LocalTime since the date is in the parent task.
     */
    @Column(name = "end_time", nullable = false)
    private LocalTime endTime;

    /**
     * Maximum bookings allowed for this slot.
     * Must be greater than 0 (enforced by database CHECK constraint).
     * Default is 1.
     */
    @Column(name = "capacity", nullable = false)
    private Integer capacity = 1;

    /**
     * Current number of bookings for this slot.
     * Must be between 0 and capacity (enforced by database CHECK constraint).
     * This field should be updated atomically when bookings are created/cancelled.
     */
    @Column(name = "booked_count", nullable = false)
    private Integer bookedCount = 0;

    /**
     * Timestamp when the slot was created.
     * Automatically set on persist.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp when the slot was last updated.
     * Automatically updated on modification.
     */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /**
     * Pre-persist callback to set timestamps.
     */
    @PrePersist
    protected void onCreate() {
        LocalDateTime now = LocalDateTime.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Pre-update callback to update the modified timestamp.
     */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }

    /**
     * Convenience constructor for creating a slot with required fields.
     *
     * @param task      the appointment task this slot belongs to
     * @param startTime the start time of the slot
     * @param endTime   the end time of the slot
     * @param capacity  the maximum capacity
     */
    public AppointmentSlot(AppointmentTask task, LocalTime startTime, LocalTime endTime, Integer capacity) {
        this.task = task;
        this.startTime = startTime;
        this.endTime = endTime;
        this.capacity = capacity;
    }

    /**
     * Full constructor for creating a slot with all fields.
     *
     * @param task        the appointment task this slot belongs to
     * @param startTime   the start time of the slot
     * @param endTime     the end time of the slot
     * @param capacity    the maximum capacity
     * @param bookedCount the current booking count
     */
    public AppointmentSlot(AppointmentTask task, LocalTime startTime, LocalTime endTime,
                           Integer capacity, Integer bookedCount) {
        this.task = task;
        this.startTime = startTime;
        this.endTime = endTime;
        this.capacity = capacity;
        this.bookedCount = bookedCount;
    }

    /**
     * Check if the slot has available capacity.
     *
     * @return true if there are available spots, false otherwise
     */
    @Transient
    public boolean hasAvailableCapacity() {
        return bookedCount < capacity;
    }

    /**
     * Get the number of remaining available spots.
     *
     * @return the number of available spots
     */
    @Transient
    public int getAvailableCapacity() {
        return capacity - bookedCount;
    }

    /**
     * Increment the booked count by one.
     * Should be called within a transaction when creating a booking.
     *
     * @return true if increment was successful, false if slot is full
     */
    public boolean incrementBookedCount() {
        if (bookedCount < capacity) {
            bookedCount++;
            return true;
        }
        return false;
    }

    /**
     * Decrement the booked count by one.
     * Should be called within a transaction when cancelling a booking.
     *
     * @return true if decrement was successful, false if already at 0
     */
    public boolean decrementBookedCount() {
        if (bookedCount > 0) {
            bookedCount--;
            return true;
        }
        return false;
    }
}
