package org.example.appointment_system.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * AppointmentTask entity representing a bookable appointment task.
 *
 * <p>This entity represents a specific appointment opportunity that merchants
 * create for their services. Each task is associated with a service item and
 * has a specific date. Tasks contain time slots that users can book.</p>
 *
 * <p>The entity contains:</p>
 * <ul>
 *   <li>Associated service item</li>
 *   <li>Task title and description</li>
 *   <li>Task date</li>
 *   <li>Total capacity for the entire task</li>
 *   <li>Active status for availability control</li>
 * </ul>
 */
@Entity
@Table(name = "appointment_tasks", indexes = {
    @Index(name = "idx_task_service_id", columnList = "service_id"),
    @Index(name = "idx_task_date", columnList = "task_date"),
    @Index(name = "idx_task_active", columnList = "active"),
    @Index(name = "idx_task_service_date", columnList = "service_id, task_date")
})
@Getter
@Setter
@NoArgsConstructor
public class AppointmentTask {

    /**
     * Unique identifier for the appointment task.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The service item that this appointment task is associated with.
     * Many-to-one relationship with ServiceItem.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "service_id", nullable = false)
    private ServiceItem service;

    /**
     * The title of the appointment task.
     * Required field, displayed to customers.
     */
    @Column(name = "title", nullable = false, length = 100)
    private String title;

    /**
     * Optional description of the appointment task.
     * Can provide additional details about this specific task.
     */
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;

    /**
     * The date of the appointment task.
     * Used for scheduling and filtering.
     */
    @Column(name = "task_date", nullable = false)
    private LocalDate taskDate;

    /**
     * Maximum total bookings for this task.
     * This is the overall capacity limit.
     * Default is 1.
     */
    @Column(name = "total_capacity", nullable = false)
    private Integer totalCapacity = 1;

    /**
     * Whether the appointment task is active and available for booking.
     * Supports soft-delete: inactive tasks are hidden but not removed.
     */
    @Column(name = "active", nullable = false)
    private Boolean active = true;

    /**
     * Timestamp when the appointment task was created.
     * Automatically set on persist.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp when the appointment task was last updated.
     * Automatically updated on modification.
     */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /**
     * Pre-persist callback to set timestamps.
     */
    @PrePersist
    protected void onCreate() {
        LocalDateTime now = LocalDateTime.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Pre-update callback to update the modified timestamp.
     */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }

    /**
     * Convenience constructor for creating an appointment task with required fields.
     *
     * @param service       the service item this task belongs to
     * @param title         the task title
     * @param taskDate      the date of the task
     * @param totalCapacity the maximum capacity
     */
    public AppointmentTask(ServiceItem service, String title, LocalDate taskDate, Integer totalCapacity) {
        this.service = service;
        this.title = title;
        this.taskDate = taskDate;
        this.totalCapacity = totalCapacity;
    }

    /**
     * Full constructor for creating an appointment task with all fields.
     *
     * @param service       the service item this task belongs to
     * @param title         the task title
     * @param description   the task description
     * @param taskDate      the date of the task
     * @param totalCapacity the maximum capacity
     * @param active        whether the task is active
     */
    public AppointmentTask(ServiceItem service, String title, String description,
                           LocalDate taskDate, Integer totalCapacity, Boolean active) {
        this.service = service;
        this.title = title;
        this.description = description;
        this.taskDate = taskDate;
        this.totalCapacity = totalCapacity;
        this.active = active;
    }

    /**
     * Check if this task is active.
     * Convenience method for better readability.
     *
     * @return true if the task is active
     */
    @Transient
    public boolean isActive() {
        return Boolean.TRUE.equals(this.active);
    }
}
