package org.example.appointment_system.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.example.appointment_system.enums.BookingStatus;

import java.time.LocalDateTime;

/**
 * Booking entity representing a user's appointment booking.
 *
 * <p>This entity represents a booking made by a user for a specific time slot.
 * Each booking is associated with a user and an appointment slot.</p>
 *
 * <p>The entity uses optimistic locking via the @Version annotation to handle
 * concurrent booking attempts. When two users try to book the last available
 * slot simultaneously, only one will succeed.</p>
 *
 * <p>Booking lifecycle:</p>
 * <ul>
 *   <li>PENDING - Initial state after booking creation</li>
 *   <li>CONFIRMED - Booking confirmed by merchant or system</li>
 *   <li>CANCELLED - Booking cancelled by user or merchant</li>
 *   <li>COMPLETED - Appointment completed</li>
 * </ul>
 */
@Entity
@Table(name = "bookings", indexes = {
    @Index(name = "idx_booking_user_id", columnList = "user_id"),
    @Index(name = "idx_booking_slot_id", columnList = "slot_id"),
    @Index(name = "idx_booking_status", columnList = "status"),
    @Index(name = "idx_booking_created", columnList = "created_at")
}, uniqueConstraints = {
    @UniqueConstraint(name = "uk_user_slot", columnNames = {"user_id", "slot_id"})
})
@Getter
@Setter
@NoArgsConstructor
public class Booking {

    /**
     * Unique identifier for the booking.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The user who made this booking.
     * Many-to-one relationship with User.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * The appointment slot that was booked.
     * Many-to-one relationship with AppointmentSlot.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "slot_id", nullable = false)
    private AppointmentSlot slot;

    /**
     * Current status of the booking.
     * Defaults to PENDING when created.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private BookingStatus status = BookingStatus.PENDING;

    /**
     * Optional remark or note from the user.
     * Can contain special requests or notes for the merchant.
     */
    @Column(name = "remark", columnDefinition = "TEXT")
    private String remark;

    /**
     * Optimistic lock version field.
     * Automatically incremented on each update.
     * Used to prevent concurrent modification conflicts.
     */
    @Version
    @Column(name = "version", nullable = false)
    private Long version = 0L;

    /**
     * Timestamp when the booking was created.
     * Automatically set on persist.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp when the booking was last updated.
     * Automatically updated on modification.
     */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /**
     * Pre-persist callback to set timestamps.
     */
    @PrePersist
    protected void onCreate() {
        LocalDateTime now = LocalDateTime.now();
        this.createdAt = now;
        this.updatedAt = now;
        if (this.status == null) {
            this.status = BookingStatus.PENDING;
        }
    }

    /**
     * Pre-update callback to update the modified timestamp.
     */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }

    /**
     * Convenience constructor for creating a booking with required fields.
     *
     * @param user the user making the booking
     * @param slot the appointment slot to book
     */
    public Booking(User user, AppointmentSlot slot) {
        this.user = user;
        this.slot = slot;
        this.status = BookingStatus.PENDING;
    }

    /**
     * Convenience constructor for creating a booking with remark.
     *
     * @param user   the user making the booking
     * @param slot   the appointment slot to book
     * @param remark optional remark for the booking
     */
    public Booking(User user, AppointmentSlot slot, String remark) {
        this.user = user;
        this.slot = slot;
        this.remark = remark;
        this.status = BookingStatus.PENDING;
    }

    /**
     * Full constructor for creating a booking with all fields.
     *
     * @param user   the user making the booking
     * @param slot   the appointment slot to book
     * @param status the initial booking status
     * @param remark optional remark for the booking
     */
    public Booking(User user, AppointmentSlot slot, BookingStatus status, String remark) {
        this.user = user;
        this.slot = slot;
        this.status = status;
        this.remark = remark;
    }

    /**
     * Confirm this booking.
     * Only works if the current status is PENDING.
     *
     * @return true if the booking was confirmed, false otherwise
     */
    public boolean confirm() {
        if (status.canConfirm()) {
            status = BookingStatus.CONFIRMED;
            return true;
        }
        return false;
    }

    /**
     * Cancel this booking.
     * Only works if the current status allows cancellation.
     *
     * @return true if the booking was cancelled, false otherwise
     */
    public boolean cancel() {
        if (status.canCancel()) {
            status = BookingStatus.CANCELLED;
            return true;
        }
        return false;
    }

    /**
     * Mark this booking as completed.
     * Only works if the current status is CONFIRMED.
     *
     * @return true if the booking was completed, false otherwise
     */
    public boolean complete() {
        if (status.canComplete()) {
            status = BookingStatus.COMPLETED;
            return true;
        }
        return false;
    }

    /**
     * Check if this booking is active (PENDING or CONFIRMED).
     *
     * @return true if the booking is active
     */
    @Transient
    public boolean isActive() {
        return status.isActive();
    }

    /**
     * Check if this booking can be cancelled.
     *
     * @return true if the booking can be cancelled
     */
    @Transient
    public boolean canCancel() {
        return status.canCancel();
    }

    /**
     * Get the user ID for convenience.
     *
     * @return the user ID, or null if user is not set
     */
    @Transient
    public Long getUserId() {
        return user != null ? user.getId() : null;
    }

    /**
     * Get the slot ID for convenience.
     *
     * @return the slot ID, or null if slot is not set
     */
    @Transient
    public Long getSlotId() {
        return slot != null ? slot.getId() : null;
    }
}
