package org.example.appointment_system.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * MerchantProfile entity representing business profiles for merchants.
 *
 * <p>This entity stores additional business information for users with the
 * MERCHANT role. Each merchant has exactly one profile linked to their user account.</p>
 *
 * <p>The profile contains:</p>
 * <ul>
 *   <li>Business name and description</li>
 *   <li>Contact information (phone, address)</li>
 *   <li>Settings stored as JSON for flexibility</li>
 * </ul>
 */
@Entity
@Table(name = "merchant_profiles", indexes = {
    @Index(name = "idx_merchant_user_id", columnList = "user_id"),
    @Index(name = "idx_merchant_business_name", columnList = "business_name")
})
@Getter
@Setter
@NoArgsConstructor
public class MerchantProfile {

    /**
     * Unique identifier for the merchant profile.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The user account associated with this merchant profile.
     * One-to-one relationship (user_id is unique in the database).
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false, unique = true)
    private User user;

    /**
     * The business name of the merchant.
     * Required field, displayed to customers.
     */
    @Column(name = "business_name", nullable = false, length = 100)
    private String businessName;

    /**
     * Optional description of the business.
     * Can be used to describe services offered.
     */
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;

    /**
     * Contact phone number.
     * Optional but recommended for customer contact.
     */
    @Column(name = "phone", length = 20)
    private String phone;

    /**
     * Business address.
     * Optional, useful for physical locations.
     */
    @Column(name = "address", length = 255)
    private String address;

    /**
     * Merchant settings stored as JSON.
     * Contains configuration like session timeout, notification preferences, etc.
     * Example: {"sessionTimeout": 3600, "notifications": true, "timezone": "Asia/Shanghai"}
     */
    @Column(name = "settings", columnDefinition = "JSON")
    private String settings;

    /**
     * Timestamp when the profile was created.
     * Automatically set on persist.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp when the profile was last updated.
     * Automatically updated on modification.
     */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /**
     * Pre-persist callback to set timestamps.
     */
    @PrePersist
    protected void onCreate() {
        LocalDateTime now = LocalDateTime.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Pre-update callback to update the modified timestamp.
     */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }

    /**
     * Convenience constructor for creating a merchant profile.
     *
     * @param user         the associated user account
     * @param businessName the business name
     */
    public MerchantProfile(User user, String businessName) {
        this.user = user;
        this.businessName = businessName;
    }

    /**
     * Full constructor for creating a merchant profile with all fields.
     *
     * @param user         the associated user account
     * @param businessName the business name
     * @param description  the business description
     * @param phone        the contact phone
     * @param address      the business address
     * @param settings     the JSON settings
     */
    public MerchantProfile(User user, String businessName, String description,
                           String phone, String address, String settings) {
        this.user = user;
        this.businessName = businessName;
        this.description = description;
        this.phone = phone;
        this.address = address;
        this.settings = settings;
    }
}
