package org.example.appointment_system.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.example.appointment_system.enums.ServiceCategory;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * ServiceItem entity representing services offered by merchants.
 *
 * <p>This entity stores service information that merchants can offer to customers.
 * Each service item belongs to a specific merchant and can be associated with
 * multiple appointment tasks.</p>
 *
 * <p>The entity contains:</p>
 * <ul>
 *   <li>Service name and description</li>
 *   <li>Category classification</li>
 *   <li>Duration (in minutes)</li>
 *   <li>Price</li>
 *   <li>Active status for soft-delete functionality</li>
 * </ul>
 */
@Entity
@Table(name = "service_items", indexes = {
    @Index(name = "idx_service_merchant_id", columnList = "merchant_id"),
    @Index(name = "idx_service_category", columnList = "category"),
    @Index(name = "idx_service_active", columnList = "active")
})
@Getter
@Setter
@NoArgsConstructor
public class ServiceItem {

    /**
     * Unique identifier for the service item.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The merchant profile that owns this service item.
     * Many-to-one relationship with MerchantProfile.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "merchant_id", nullable = false)
    private MerchantProfile merchant;

    /**
     * The name of the service.
     * Required field, displayed to customers.
     */
    @Column(name = "name", nullable = false, length = 100)
    private String name;

    /**
     * Optional description of the service.
     * Can provide details about what the service includes.
     */
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;

    /**
     * Category of the service.
     * Used for classification and filtering.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "category", nullable = false)
    private ServiceCategory category = ServiceCategory.GENERAL;

    /**
     * Duration of the service in minutes.
     * Default is 30 minutes.
     */
    @Column(name = "duration", nullable = false)
    private Integer duration = 30;

    /**
     * Price of the service.
     * Uses BigDecimal for precise monetary calculations.
     * Default is 0.00 (free or price to be determined).
     */
    @Column(name = "price", nullable = false, precision = 10, scale = 2)
    private BigDecimal price = BigDecimal.ZERO;

    /**
     * Whether the service is active and available for booking.
     * Supports soft-delete: inactive services are hidden but not removed.
     */
    @Column(name = "active", nullable = false)
    private Boolean active = true;

    /**
     * Timestamp when the service item was created.
     * Automatically set on persist.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp when the service item was last updated.
     * Automatically updated on modification.
     */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /**
     * Pre-persist callback to set timestamps.
     */
    @PrePersist
    protected void onCreate() {
        LocalDateTime now = LocalDateTime.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Pre-update callback to update the modified timestamp.
     */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }

    /**
     * Convenience constructor for creating a service item with required fields.
     *
     * @param merchant   the merchant profile that owns this service
     * @param name       the service name
     * @param category   the service category
     * @param duration   the service duration in minutes
     * @param price      the service price
     */
    public ServiceItem(MerchantProfile merchant, String name, ServiceCategory category,
                       Integer duration, BigDecimal price) {
        this.merchant = merchant;
        this.name = name;
        this.category = category;
        this.duration = duration;
        this.price = price;
    }

    /**
     * Full constructor for creating a service item with all fields.
     *
     * @param merchant    the merchant profile that owns this service
     * @param name        the service name
     * @param description the service description
     * @param category    the service category
     * @param duration    the service duration in minutes
     * @param price       the service price
     * @param active      whether the service is active
     */
    public ServiceItem(MerchantProfile merchant, String name, String description,
                       ServiceCategory category, Integer duration, BigDecimal price, Boolean active) {
        this.merchant = merchant;
        this.name = name;
        this.description = description;
        this.category = category;
        this.duration = duration;
        this.price = price;
        this.active = active;
    }
}
