package org.example.appointment_system.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.example.appointment_system.enums.UserRole;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * User entity representing all user accounts in the system.
 *
 * <p>This entity stores user information for three types of users:</p>
 * <ul>
 *   <li>Administrators (ADMIN) - Full system access</li>
 *   <li>Merchants (MERCHANT) - Business owners who manage appointments</li>
 *   <li>Users (USER) - End users who book appointments</li>
 * </ul>
 *
 * <p>The entity uses auto-generated IDs and timestamps for audit purposes.</p>
 */
@Entity
@Table(name = "users", indexes = {
    @Index(name = "idx_users_username", columnList = "username"),
    @Index(name = "idx_users_email", columnList = "email"),
    @Index(name = "idx_users_role", columnList = "role")
})
@Getter
@Setter
@NoArgsConstructor
public class User implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * Unique identifier for the user.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique username for authentication.
     * Must be between 3-50 characters.
     */
    @Column(name = "username", nullable = false, unique = true, length = 50)
    private String username;

    /**
     * Hashed password using BCrypt.
     * Never stored in plain text.
     */
    @Column(name = "password", nullable = false, length = 255)
    private String password;

    /**
     * Unique email address.
     * Used for notifications and account recovery.
     */
    @Column(name = "email", nullable = false, unique = true, length = 100)
    private String email;

    /**
     * User role determining access permissions.
     * Defaults to USER role.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "role", nullable = false, length = 20)
    private UserRole role;

    /**
     * Flag indicating if the user account is enabled.
     * Disabled accounts cannot authenticate.
     */
    @Column(name = "enabled", nullable = false)
    private boolean enabled = true;

    /**
     * Timestamp when the user was created.
     * Automatically set on persist.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp when the user was last updated.
     * Automatically updated on modification.
     */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /**
     * Pre-persist callback to set timestamps.
     */
    @PrePersist
    protected void onCreate() {
        LocalDateTime now = LocalDateTime.now();
        this.createdAt = now;
        this.updatedAt = now;
        if (this.role == null) {
            this.role = UserRole.USER;
        }
    }

    /**
     * Pre-update callback to update the modified timestamp.
     */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }

    /**
     * Convenience constructor for creating users.
     *
     * @param username the username
     * @param password the hashed password
     * @param email    the email address
     * @param role     the user role
     */
    public User(String username, String password, String email, UserRole role) {
        this.username = username;
        this.password = password;
        this.email = email;
        this.role = role;
    }
}
